### ISSUE TITLE
org.snaker.engine.model.ProcessModel Serialization By FastJson Err:

### ISSUE THREAD

**Issue by FictionDk** [snakerflow-starter/snakerflow-spring-boot-starter#4]
`org.snaker.engine.model.ProcessModel`使用FastJson序列化会报错;`Expected ',' instead of ''`
```
exception [Handler dispatch failed; nested exception is java.lang.StackOverflowError] with root cause
java.lang.StackOverflowError: null
	at java.lang.reflect.InvocationTargetException.<init>(InvocationTargetException.java:72)
	at sun.reflect.GeneratedMethodAccessor53.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alibaba.fastjson.util.FieldInfo.get(FieldInfo.java:492)
	at com.alibaba.fastjson.serializer.FieldSerializer.getPropertyValue(FieldSerializer.java:148)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.getFieldValuesMap(JavaBeanSerializer.java:763)
```

使用 FastJson 序列化`org.snaker.engine.DBAccess.public Process getProcess(String id)`返回的`Process`包含`ProcessModel`字段.返回异常

**Comment by bigfish1129** [comment]
可能是你的流程配置文件有点问题
